name: CI

on:
  push:
    branches:
    - main

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    uses: actions/checkout@v3

    -run: rojo-build -o game.rbxl
    -run: rbxcloud experience publish --f game.rbxl --p 18331518253 --u 6214587694 --t published --a ${{ secrects.API_KEY }}

   