name: RBXDeploy

on:
  push:
    branches:
    - main

jobs:

    deploy:
      name: deploy
      runs-on: ubuntu-latest

      strategy:
      matrix:
    node-version: ['18.x', '20.x']

      steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      -run: rojo build -o game.rbxlx
      -run: rbxcloud experience publish -f game.rbxlx -p 18331518253 -u 6214587694 -t published -a ${{ secrets.API_KEY }}

   