name: RBXDeploy

on:
  push:
    branches:
    - main

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
      uses: actions/checkout@v3
      - uses: LPGhatguy/aftman
      name: Install aftman
      with:  
        version: "^0.3.0"


    -run: npm run build
    -run: rojo build -o build.rbxlx
    -run: rbxcloud experience publish --f game.rbxl --p 18331518253 --u 6214587694 --t published --a ${{ secrets.API_KEY }}

   