name: RBXDeploy

on:
  push:
    branches:
    - main

jobs:
    deploy:
      name: deploy
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: ['18.x', '20.x']
      steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      -run: rojo build -o game.rbxlx

      - name: Publish
        shell: bash
        env:
          UID: 6214587694              # Universe ID
          PID: 18331518253              # Place ID
          API_KEY: ${{ secrets.API_KEY }} # API Key (keep this in your GitHub Repository Secrets)
          FILE: game.rbxlx         # Roblox place file (e.g. might have a step before this to build the file with Rojo)

        run: rbxcloud experience publish -a "$API_KEY" -u "$UID" -p "$PID" -t published -f "$FILE"